apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-mongo-ce-mongo-ce-sa-sa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-mongo-ce
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-mongo-ce/mongo-ce-sa-sa
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-mongo-ce-ocp4_cp4i
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
        - /secrets
      kind: ServiceAccount
