apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb-kubernetes-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
rules:
- "apiGroups":
  - "*"
  "resourceNames": null
  "resources":
  - "*"
  "verbs":
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongodb-kubernetes-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-kubernetes-operator
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator
  namespace: gitops-mongo-ce
---
